version: '3.4'

services:
  studentsmanager.ui:
    image: ${DOCKER_REGISTRY-}studentsmanagerui
    container_name: studentsmanagerui
    ports:
      - 8088:8088
    build:
      context: ./StudentsManager-UI
      dockerfile: Dockerfile
    networks:
      - students-network
    depends_on:
      - "redis.students"

  redis.students:
    image: redis:alpine
    ports:
      - "16379:6379"
    networks:
      - students-network
 
  studentsmanager.api:
    image: ${DOCKER_REGISTRY-}studentsmanagerapi
    container_name: studentsmanagerapi
    ports:
      - 8089:8089
    build:
      context: ./StudentsManager
      dockerfile: StudentsManager.Api/Dockerfile
    networks:
      - students-network
    depends_on:
      - "db"

  db:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "VcDERqwfaDs4bkEHDJ1H"
    ports:
      - "1401:1433"
    networks:
      - students-network

networks: 
    students-network:
      external: true